### ISSUE TITLE
Gulp throws error on sails lift

### ISSUE THREAD

**Issue by robrigo** [Karnith/sails-for-gulp#12]
Attempting to configure sails using Postgres DB, waterlock, and using gulp to build semantic UI. I believe this error started when I added postgres. This is my first time using sails so I probably should have kept using the latest stable version but I got tempted to use your version with gulp. The sails server finishes lifting but it would seem that all of the tasks aren't completed as my .tmp folder does not have the public assets available.

```
error: Gulp :: events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new Parser (/usr/local/lib/node_modules/sails/node_modules/gulp-less/node_modules/less/lib/less/parser.js:333:27)
    at Object.less.render (/usr/local/lib/node_modules/sails/node_modules/gulp-less/node_modules/less/lib/less/index.js:18:22)
    at Transform._transform (/usr/local/lib/node_modules/sails/node_modules/gulp-less/index.js:42:10)
    at Transform._read (/usr/local/lib/node_modules/sails/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/usr/local/lib/node_modules/sails/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/sails/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/sails/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Wri
error: Gulp :: table.write (/usr/local/lib/node_modules/sails/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/local/lib/node_modules/sails/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/local/lib/node_modules/sails/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
```

Thanks for your work!

**Comment by Karnith** [comment]
Hi,

Thanks for trying this. It's still in development and a branch that is breaking away from the main sails project (kind of like centos did with red hat). If you want to use gulp, use the gulp generators for now, unless you'd like to help troubleshoot issues..

I'll look into this for you.

Thx
Karnith

Sent from my Windows Phone

**Comment by robrigo** [comment]
Happy to help where I can, I'm still getting my bearings w.r.t. to sails and front-end build tools.
